change-log
changeLog
	^ {
		'Warnings about uncommitted changes before merging only occur when not up-to-date.'.
		'The list of branches, remote branches, etc. is now a tree. Hover over the root nodes to get an explanation.'.
		'A change log is shown after a self-update (the one you are currently seeing :)).'.
		'Before a manual self-update is done, git-s checks whether a new version exists and prompts the user to cancel if not.'.
		'Add support for the terminal emulator Ptyxis.'.
	}